### ISSUE TITLE
Travis CI job is failing after adding the release specific tasks

### ISSUE THREAD

**Issue by rajneesh-ops** [KohlsTechnology/eunomia#125]
These are the error messages:-
![image](https://user-images.githubusercontent.com/56915603/67955731-07fe5080-fc19-11e9-8124-315030592b85.png)

These are the raw logs:-
https://api.travis-ci.com/v3/job/251334041/log.txt

**Comment by seanmalloy** [comment]
I was just able to rebuild [this CI job from Travis](https://travis-ci.com/KohlsTechnology/eunomia/builds/134436845). See also the [raw log](https://api.travis-ci.com/v3/job/251557035/log.txt). My best guess is that this was just a glitch in TravisCI because as of right now I cannot reproduce this problem.

@rhalat and @rajneesh-ops I'll keep this issue open until the end of next week. Please add additional details here if you run into this issue again.

**Comment by akavel** [comment]
@seanmalloy, the bulid you link to as successful uses a different, improved .travis.yml. The `openssl` call there [is guarded with `if [ "$TRAVIS_TAG" ]; then openssl ... fi`](https://travis-ci.com/KohlsTechnology/eunomia/builds/134436845#L620). The current .travis.yml on main branch is still not working, see e.g. #128 ([failing build](https://travis-ci.com/KohlsTechnology/eunomia/builds/134858438#L620)).

**Comment by rhalat** [comment]
@seanmalloy I added commit to https://github.com/KohlsTechnology/eunomia/pull/86 and build is still failing with the same error
