### ISSUE TITLE
Automatically Create eunomia-templates ConfigMap

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#162]
**Is your feature request related to a problem? Please describe.**

[OLM](https://github.com/operator-framework/operator-lifecycle-manager) cannot automatically create a `ConfigMap` when deploying an operator. Currently the eunomia operator requires the eunomia-templates ConfigMap to be created at deployment time. This is preventing seamless installation of eunomia using OLM from operatorhub.io.

**Describe the solution you'd like**

The eunomia operator should automatically create a default eunomia-templates ConfigMap if one does not already exist.

**Describe alternatives you've considered**

Require users to manually create the required ConfigMap when deploying eunomia using OLM.

**What version of eunomia are you using?**

eunomia version: v0.0.3

**Additional context**

This feature is required before we can the eunomia listed on operatorhub.io. See operator-framework/community-operators/pull/902.

**Comment by seanmalloy** [comment]
Here is where the ConfigMap currently lives ... https://github.com/KohlsTechnology/eunomia/blob/master/deploy/helm/eunomia-operator/templates/configmap.yaml

**Comment by sbar95** [comment]
So far:
pod/eunomia-operator cannot start because configmap "eunomia-template" isn't found. Even if eunomia-operator could automatically create this configmap, it wouldn't change anything (in current setup) because for eunomia-operator to start there has to be this configmap in the first place.
As for now eunomia-operator cannot start without the configmap.

I'm going to investigate this further.

**Comment by Smiley73** [comment]
It doesn't have to create the configmap automatically. Why not do it this way:
- compile eunomia and add the templates to the code
- at start time, if configmap is missing, simply use what has been compiled-in
- log a warning message/event that the default template was used

**Comment by seanmalloy** [comment]
@Smiley73 I believe this approach seems reasonable. @sbar95 let us know if you think the approach suggested by @Smiley73 will work.

**Comment by sbar95** [comment]
Thanks @Smiley73, after yesterday's research your method or something similar seems to be a viable way to achieve what we want. @seanmalloy I'm going to start implementing it.

**Comment by raffaelespazzoli** [comment]
I have another operator with a similar issue. I solved the issue packaging the content of the configmap in a go source (similar to the concept of java resources). I did it with this tool `go-bindata` (https://github.com/go-bindata/go-bindata).
For reference this is the operator where I'm using that technique:
https://github.com/raffaelespazzoli/must-gather-operator

**Comment by akavel** [comment]
Could we just dump the 2 yamls as 2 big multiline strings inside eunomia, and remove them from disk? thus removing the need for go-bindata, as well as ConfigMap?

If we want users to be able to override the files, maybe we could just check the environment variables we're already checking, and if they're non-empty, load yaml from the paths they're pointing to instead of from the 2 big strings?

**Comment by sbar95** [comment]
Yes, we could get rid of the configmap for good. We could only leave some information in the documentation that if the user wants to override the default configuration, he can use his own configmap.
