### ISSUE TITLE
GitOpsConfig CR triggers not working as expected

### ISSUE THREAD

**Issue by rhalat** [KohlsTechnology/eunomia#182]
**What version of eunomia are you using?**

eunomia version: v0.0.4

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-09-12T23:41:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

I created GitOpsConfig CR for eunomia with triggers type "Webhook".
```
  triggers:
  - type: Webhook
```

**What did you expect to see?**
I expect to see eunomia waiting for webhook POST request to trigger job creation.

**What did you see instead?**
Eunomia is creating 4 or 5 jobs per hour without webhook configured, so it can't receive any POST request. I believe it's acting like there is "Change" trigger set. 

Here is example log from eunomia operator pod:

{"level":"info","ts":1575033916.0201108,"logger":"controller_gitopsconfig","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}

I also noticed that when I changed it to periodic there were like both triggers running - cronjob as I set it in periodic and these 4-5 jobs per hour (Change I guess).

**Comment by akavel** [comment]
Hm; but then, if trigger type was set to `Change`, I'm not sure either why would we expect 4-5 jobs per hour generated out of thin air anyway?... 😮 🤔

This way or the other, from an initial peek at the code, it looks to me that we don't actually have an easy technical way to find out where does a Reconciliation request come from! 😕 the reconcile.Request in the official k8s Go client apparently only has two fields — Name and Namespace...

I wonder, should we maybe remove the Webhook trigger type in the CRD and only leave the Change one? @Smiley73 , do you maybe know any historical background behind this split, by chance? Was there some important intended difference in behavior of the Webhook trigger, that the Change trigger would not be enough for? As far as implementation goes, there seems to be absolutely no difference between them currently, unless I'm missing something...

**Comment by Smiley73** [comment]
@akavel not sure on the background. The intention was to have it configurable which trigger is enabled. As long as we still can have the webhook optional, then we should be fine. One could argue "don't configure the webhook on git and it won't get triggered" is enough. ;-)

**Comment by rhalat** [comment]
When I ran eunomia locally it worked fine, so most probably this is environment/configuration issue.

**Comment by seanmalloy** [comment]
We need both the `Change` and `Webhook` triggers. The `Change` trigger will start a reconciliation when an `GitOpsConfig` CR is changed in the k8s cluster. The `Webhook` trigger will start a reconciliation when a a change is made to the templates or parameters in a git repo that is referenced by a `GitOpsConfig` CR.

We will need to fix this bug prior to the v0.1.0 release.

**Comment by akavel** [comment]
Do we have any idea how we could implement this? Personally, as of now, I don't see if we can do this if we want to keep following the architecture suggested by default for k8s operators. Do we know if it's ok for operators to not use the default channel through which reconcile.Requests arrive?

To explain: IIUC, the default suggested approach for operators is that reconciliation requests should pass through k8s mechanisms, and then they get passed to Reconcile method of operator controller. However, as far as I can see, a [reconciliation request in k8s API only has 2 fields: Namespace & Name](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile#Request) of the CR — no extra fields to add info if the source was from webhook or other place. Also, I think there may be some rate limiting mechanisms underneath, before a request is passed to Reconcile. If we wanted to stay with this model, I have no idea how to differentiate webhooks from other triggers.

The only idea I currently have how we could do this, would be to introduce separate, private channels for triggering reconciliation when a webhook was called. However, I believe we should then be careful to make sure Reconcile method cannot be called concurrently through those multiple sources, as this would make our code much more complicated. (I would suggest adding a "demultiplexer" layer, making sure any calls to Reconcile are serialized with the new private channels.)

Otherwise, @seanmalloy I'm not actually sure why we need to specifically mark a Webhook trigger in a CR. Is it not enough to let user decide if they want to POST to the webhook endpoint or not? If user does not attach a push source to the webhook endpoint, just saying "`trigger: Webhook`" won't do much for them anyway. If they do attach a push source, I don't currently understand what reason we could have to still let them make it no-op by not specifying `trigger: Webhook`?

**Comment by akavel** [comment]
Some extra note, [based on the operator-sdk docs](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg#hdr-Controller):

> Unlike http handlers, Controllers DO NOT handle events directly, but enqueue Requests to eventually reconcile the object. This means the handling of multiple events may be batched together and the full state of the system must be read for each reconcile.

**Comment by seanmalloy** [comment]
We are not able to reproduce this issue using v0.1.1. This bug can be re-opened in the future if it can be reproduced.
