### ISSUE TITLE
Deleting k8s Resources Can Hang Waiting on Finalizers

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#213]
**What version of eunomia are you using?**

eunomia version: v0.0.5

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
</pre></details>

**What did you do?**

The `kubectl delete` command in resourceManager.sh can hang forever waiting on finalizers. We should always use the `--wait=false` option with `kubectl delete`.

**What did you expect to see?**
Deleting k8s resources does not hang on finalizers.

**What did you see instead?**
In certain cases the `kubectl delete` command will wait forever on finalizers.

**Comment by sbar95** [comment]
@seanmalloy What you describe in this issue was repaired in #215. I tested it and wasn't able to reproduce any hang. I can add `--wait=false` in [resourceManager.sh](https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/base/bin/resourceManager.sh#L73) as a safety precaution but I'm not sure if it's really needed since you were logging this issue for eunomia v0.0.5 when there was [another approach](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/template-processors/base/bin/resourceManager.sh#L36-L43) of deleting resources (back then a hang could occur).

**Comment by akavel** [comment]
The specific case described by @tomsucho, that I believe was the background behind this issue, was more or less like this:

> So I run a delete for a bunch of related resources, without forcing any particular order:
> 
>     $  find ~/GIT/templates/*.j2 -exec sh -c "yq m *.yml | j2 -f yaml {} | kubectl delete -f -" \;
> 
> And then in the logs:
> 
>     ERROR: Error waiting for Deleting Network: The network resource 'XXX' is already being used by 'YYY'
> 
> So XXX can’t be deleted due to YYY being deployed in it, but we never get to the part of deleting that YYY with kubectl since it hangs waiting for the XXX to be deleted...
> For creation it is okay since even if you apply out of order, eventually all resources will be created and so it will reconcile

Given that there's a single `kubectl delete -f -` in his pipeline above, I think even though we only have one `kubectl` call in resourceManager.sh, may still get stuck. That's I believe the reason why the `--wait=false` was proposed.

**Comment by seanmalloy** [comment]
Yes ... because we are using [GCP Config Connector](https://cloud.google.com/config-connector/docs/overview) I believe we want to make sure we are not waiting too long on finalizers when deleting resources. This is why I'm proposing adding the `--wait=false` to all of our `kubectl delete` commands.

**Comment by Smiley73** [comment]
Would there be cases where we'd actually want to wait? What if the deletion fails for some reason, shouldn't we be able to report back on that status?
I'd make it a configurable item and let the user decide. This might be a good flag for v1alpha2

**Comment by seanmalloy** [comment]
@sbar95 for now as part of the v0.1.1 release we will stick with adding `--wait=false` to all of our `kubectl delete` commands.

@Smiley73 I added [this comment](https://github.com/KohlsTechnology/eunomia/issues/183#issuecomment-571348113) on the v1alpha2 issue #183, so we don't lose track of this.

**Comment by akavel** [comment]
I kinda had similar doubts as @Smiley73 initially, but now I agree with @seanmalloy's decision to push through and add it: I think it's better to go boldly — and even more so given that we're still at super early phases. Actually, I'd personally now opt for not at all making it a configurable item: my rationale being, that this way we can see if some people come complaining about it with bug reports, and only add it then, seeing that someone really needs it. Otherwise, we risk being left with an option that would be hard to ever remove, not having a way to find out if anyone uses it.
