### ISSUE TITLE
Refactor "test initialization" into separate function

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#214]
**Is your feature request related to a problem? Please describe.**

The e2e tests currently all contain the same "initialization" steps, for example issue24_test.go L17-38: https://github.com/KohlsTechnology/eunomia/blob/2562df6f11d4a8f7ecbde9bf626be592b056269a/test/e2e/issue24_test.go#L17-L38
This has resulted in quite a bit of duplicated but slightly different code which can be challenging to manage if we need to change the initialization process of a Eunomia e2e test.

An example of a difference is the `issue24_test.go` test introduced `defer DumpJobsLogsOnError(t, framework.Global, namespace)`, which would be helpful in the other tests but it has not been added to the other tests.

**Describe the solution you'd like**

The e2e test setup should be moved into a common function which is called in the e2e tests to reduce the amount of duplicate code.

**Describe alternatives you've considered**

I am not aware of other alternatives.

**What version of eunomia are you using?**

eunomia version: v0.0.5

**Additional context**

Some context from a quick discussion on https://github.com/KohlsTechnology/eunomia/pull/212#discussion_r359029304

**Comment by akavel** [comment]
Some implementation ideas:

  1.  I'd sugest creating a struct type for wrapping the objects created by the preamble (in contrast to returning multiple free-standing values from a function);
  2. my suggestion for a name for this struct would be `Context` (which, per [Go naming conventions](https://golang.org/doc/effective_go.html#package-names), will be implicitly understood to mean "e2e test context" if the type is defined in `test/e2e` package)
     - the typical convention for naming the "constructor" function for it would then be  `NewContext`
  3. I would suggest putting all the logic that was previously done in `defer` calls into a `Close() error` method on this new type.  This way, the type would fulfill the [`Closer`](https://golang.org/pkg/io/#Closer) interface, commonly implemented by the Go standard library and the wider ecosystem. (Note that this method name isn't in any way "magical" — the tests will still have to explicitly run `defer ctx.Close()`).

With all of the above, the preamble of most of the tests could then ideally look more or less like this:

    ctx, err := NewContext(t)
    if err != nil {
        t.Fatal(err)
    }
    defer ctx.Close()

Additionally:

  4. we could try to make it implement the [context.Context interface](https://golang.org/pkg/context/#Context) (for example, by [embedding](https://travix.io/type-embedding-in-go-ba40dd4264df) a [context.Context](https://golang.org/pkg/context/#Context) object and initializing it with [context.Background](https://golang.org/pkg/context/#Background) in `NewContext()`), so that we could pass `ctx` instead of `context.TODO()` in places like this: https://github.com/KohlsTechnology/eunomia/blob/2562df6f11d4a8f7ecbde9bf626be592b056269a/test/e2e/issue24_test.go#L73
  5. in future, we could consider also migrating common lines like the `Create` call above into helper methods of our new `Context` type
