### ISSUE TITLE
presentation or video

### ISSUE THREAD

**Issue by Gl4di4torRr** [KohlsTechnology/eunomia#39]
Any upcoming public presentations on eunomia?

**Comment by Smiley73** [comment]
@Gl4di4torRr  we're planning to submit a proposal for KubeCon. We definitely should be doing more, but from a Kohl's side we're a bit limited. Do you have any other ideas / suggestions?

**Comment by Gl4di4torRr** [comment]
@Smiley73 would love to just see a presentation on the journey, how you're using it at kohls, potential roadmap, etc.! :)

**Comment by Gl4di4torRr** [comment]
KubeCon would be a great place to do so

**Comment by Smiley73** [comment]
@Gl4di4torRr we have nothing official in regards to a roadmap. The GitHub issues are the closest we have. Our focus right now is getting to a production ready MVP. Our plan is to manage one namespace across a couple of clusters (including production) in a month or two via the Operator, so that we get some real world feedback. I feel strongly that we need the variable hierarchy (issue #5 ), before we can take this to the next level.
We also need as much additional help as we can get, that's why we pushed hard to release it externally. Really hoping you can contribute more too. :D

I did talk about the GitOps concept and (briefly) the Operator at the Red Hat Summit: 
 https://summit.redhat.com/conference/page/DownloadDocument?documentid=bc9f09a9-8c9d-406e-8c76-f984d1209d31
Not sure how much sense the slides make without me talking through it.
Some of the ideas for App/Dev teams would require additional operators, because I don't want to cram too much into this one. Let's take a micro-services approach and have operators do a specific thing. It'll be easier to maintain this way.

**Comment by Gl4di4torRr** [comment]
@Smiley73 totally missed your presentation at summit!
I am looking at this product for use and to contribute to :)
I will look out for you all at KubeCon or another conference where I can hear your story. Thanks!
