### ISSUE TITLE
Add sonarcloud.io

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#42]
Add sonarcloud.io to our Travis pipeline, in order to ensure high code quality.
The organization is already set up: https://sonarcloud.io/organizations/kohlstechnology
Any GitHub users in our org will get automatically added, once they register to sonarcloud.io.

**Comment by akavel** [comment]
After some initial browsing of the SonarQube report generated for eunomia, I would advise that we should approach this tool cautiously, carefully, and with consideration. In the current (default?) configuration, I see it as dangerously overzealous and opinionated to the extreme; it seems to be taking many vague ideas and "good practices" too literally and  strictly, and taking them way too far into [FUD](https://en.wikipedia.org/wiki/FUD) territory.

***However***, with the above caveat, I believe we can totally still extract value from this tool if we approach it thoughtfully — assuming it has enough configurability and customizability. Specifically, my advice would be to start from a clean slate, with *all and every rule disabled*. Only then, gradually, cherry-pick and enable some if we like them (but disable them again with prejudice if we think they are more harm than gain). For example, from the first dozen or so on the list, I kinda potentially like the following ones:

- https://sonarcloud.io/organizations/kohlstechnology/rules?languages=go&open=go%3AS3923
- https://sonarcloud.io/organizations/kohlstechnology/rules?languages=go&open=go%3AS1940
- https://sonarcloud.io/organizations/kohlstechnology/rules?languages=go&open=go%3AS1125
- ( https://sonarcloud.io/organizations/kohlstechnology/rules?languages=go&open=go%3AS134 - this one is tricky: the rule is potentially useful, though more as a hint during code review, not as an absolute rule; however I strongly dislike the description text; this could be a nice case to let us explore whether we can edit description text, as well as any "actions" and properties attached, ideally to have it only run as a hint during code reviews)

In comparison, some quick examples of  **false positives** that jumped at me as dangerous and "crying wolf" immediately when I started browsing the report generated by SQ for eunomia:

  - zz_generated.*.go files in our repo are auto-generated by third party tools, so we don't want to do any checks on them - e.g.: https://sonarcloud.io/project/issues?id=eunomia&issues=AW-43e0ZRIhFgpOtR6WU&open=AW-43e0ZRIhFgpOtR6WU
  - duplicated lines in tests - there will always be a lot of duplication in tests and this is OK more often than not - tests are somewhat different kind of code, and because of different goals, they are measured by different standards - for example, I much prefer tests that are explicit, quickly and easily readable, and dumb - *even if duplicated* - than if they are too smart - example "duplication" report: https://sonarcloud.io/code?id=eunomia&line=307&selected=eunomia%3Atest%2Fe2e%2Fstatus_test.go
  - TODOs marked as "code smells" - I am not sure I understand the goal of this; I much prefer if someone writes TODO for missing code, than if they were discouraged from writing it to "avoid introducing code smell" - this wouldn't remove the problem, but rather sweep it under the rug instead - example: https://sonarcloud.io/project/issues?id=eunomia&issues=AW-43ezHRIhFgpOtR6V4&open=AW-43ezHRIhFgpOtR6V4
  - "Code Complexity" with level "critical" when a function has 13 if-s, over half of them being "if err != nil" - first of all, absolutely not something "critical", this is pure fearmongering; an app crashing on PROD may be considered *critical*; data races are *critical*; 13 if-s are definitely *not critical*; I get it, the function is complex, let's talk about it, maybe we can think of something better (or maybe not?) — how about a dismissable warning during code review instead?  - https://sonarcloud.io/project/issues?id=eunomia&issues=AW-43ezHRIhFgpOtR6WC&open=AW-43ezHRIhFgpOtR6WC
